// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfoOSbJCV6ydNLi1z6cCrrTx7UaRQDZw',
    appId: '1:721102588509:web:eba1afa19430fa6349dbb4',
    messagingSenderId: '721102588509',
    projectId: 'dark-media-getx',
    authDomain: 'dark-media-getx.firebaseapp.com',
    storageBucket: 'dark-media-getx.appspot.com',
    measurementId: 'G-EQWNDH852Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFG-MlAGXzFad7r1nkeeGAvzEAeuJFW2M',
    appId: '1:721102588509:android:05d0ebd34469197449dbb4',
    messagingSenderId: '721102588509',
    projectId: 'dark-media-getx',
    storageBucket: 'dark-media-getx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYlH3SMlMPrDs4AJdYTRmtWsboYRYUOY',
    appId: '1:721102588509:ios:f1dba08a2e1d436a49dbb4',
    messagingSenderId: '721102588509',
    projectId: 'dark-media-getx',
    storageBucket: 'dark-media-getx.appspot.com',
    iosBundleId: 'com.example.clonetiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYlH3SMlMPrDs4AJdYTRmtWsboYRYUOY',
    appId: '1:721102588509:ios:8cacbeb4b366418849dbb4',
    messagingSenderId: '721102588509',
    projectId: 'dark-media-getx',
    storageBucket: 'dark-media-getx.appspot.com',
    iosBundleId: 'com.example.clonetiktok.RunnerTests',
  );
}
